name: Build All Linux ARM64 Jetson CUDA 12.6

on:
  workflow_dispatch:
    inputs:
      onnxruntime-version:
        type: string
        description: "ONNX Runtime version (e.g. 1.18.0)"
        required: true
      runs-on:
        type: string
        description: "GitHub Runner OS version (e.g. ubuntu-24.04, ubuntu-22.04)"
        default: "ubuntu-24.04"
        required: false

jobs:
  build:
    uses: ./.github/workflows/build-runner-gcc13.yml

    strategy:
      fail-fast: false
      matrix:
        include:
          - target: aarch64-unknown-linux-gnu
            args: "-A aarch64 --cuda --xnnpack -N"
            static: true
            feature-set: cu12
            cuda-version: "12.6.1"
            # 动态使用输入的 runs-on 值，如果未输入则使用默认值
            runs-on: ${{ inputs.runs-on }}
          - target: aarch64-unknown-linux-gnu
            args: "-A aarch64 --cuda --xnnpack -N"
            static: false
            feature-set: cu12
            cuda-version: "12.6.1"
            # 动态使用输入的 runs-on 值，如果未输入则使用默认值
            runs-on: ${{ inputs.runs-on }}

    with:
      onnxruntime-version: ${{ inputs.onnxruntime-version }}
      target: ${{ matrix.target }}
      args: ${{ matrix.args }}
      static: ${{ matrix.static }}
      feature-set: ${{ matrix.feature-set }}
      cuda-version: ${{ matrix.cuda-version }}
      runs-on: ${{ matrix.runs-on }}
